export enum ActionType {
    FETCH_BIO = "fetch_bio",
    FETCH_BIO_SUCCESS = "fetch_bio_success",
    SAVE_BIO = "save_bio",
    SAVE_BIO_SUCCESS = "save_bio_success",
    SAVE_CURRENT_BIO = "save_current_bio",
    UPDATE_BIO = "update_bio",
    UPDATE_BIO_SUCCESS = "update_bio_success",
    BIO_ERROR = "bio_error",

    FETCH_EDUCATIONS = "fetch_educations",
    FETCH_EDUCATIONS_SUCCESS = "fetch_educations_success",
    FORM_UPDATE_EDUCATION = "form_update_education",
    FORM_UPDATE_EDUCATION_SUCCESS = "form_update_education_success",
    UPDATE_EDUCATIONS = "update_educations",
    UPDATE_EDUCATIONS_SUCCESS = "update_educations_success",
    ADD_EDUCATION = "add_education",
    CANCEL_ADD_EDUCATION = "cancel_add_education",
    ADD_EDUCATION_SUCCESS = "add_education_success",
    SWITCH_ADD_EDUCATION = "switch_add_education",
    SAVE_NEW_EDUCATION = "save_new_education",
    SAVE_NEW_EDUCATION_SUCCESS = "save_new_education_success",
    DELETE_EDUCATION = "delete_education",
    DELETE_EDUCATION_SUCCESS = "delete_education_success",
    EDUCATION_ERROR = "education_error",
}
